name = str(input("Enter your name: "))
print(name.upper().isupper())
print(name.upper())
print(name.lower().islower())
print(name.lower())
print(len(name))
lenght = len(name)
print(lenght)
print(name[0])
print(name[-1])
print(name[3])
